"""empty message

Revision ID: a8d60a5e766c
Revises: d56bc6b52848
Create Date: 2019-04-29 05:35:29.868460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a8d60a5e766c'
down_revision = 'd56bc6b52848'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('athletes', 'extra')
    op.add_column('registrations', sa.Column('extra', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registrations', 'extra')
    op.add_column('athletes', sa.Column('extra', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
