"""empty message

Revision ID: d56bc6b52848
Revises: 01dfb93e0e91
Create Date: 2019-04-29 04:46:08.933388

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd56bc6b52848'
down_revision = '01dfb93e0e91'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tracks', 'status')
    op.drop_column('tracks', 'expected_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tracks', sa.Column('expected_time', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('tracks', sa.Column('status', postgresql.ENUM('not_started', 'started', 'ended', name='status'), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
