"""empty message

Revision ID: 1bbe48788de1
Revises: d5e17de77f6d
Create Date: 2019-05-01 01:50:55.343945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bbe48788de1'
down_revision = 'd5e17de77f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=60), nullable=False),
    sa.Column('status', sa.Enum('not_started', 'started', 'ended', name='status'), nullable=False),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('last_ev_id', sa.Integer(), nullable=True),
    sa.Column('next_ev_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['last_ev_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['next_ev_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('last_ev_id'),
    sa.UniqueConstraint('next_ev_id'),
    sa.UniqueConstraint('track_id', 'name')
    )
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_name'), 'events', ['name'], unique=False)
    op.create_index(op.f('ix_events_track_id'), 'events', ['track_id'], unique=False)
    op.create_table('results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('athlete_id', sa.Integer(), nullable=False),
    sa.Column('value', sa.Integer(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['athlete_id'], ['athletes.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', 'athlete_id')
    )
    op.create_index(op.f('ix_results_athlete_id'), 'results', ['athlete_id'], unique=False)
    op.create_index(op.f('ix_results_event_id'), 'results', ['event_id'], unique=False)
    op.create_index(op.f('ix_results_id'), 'results', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_results_id'), table_name='results')
    op.drop_index(op.f('ix_results_event_id'), table_name='results')
    op.drop_index(op.f('ix_results_athlete_id'), table_name='results')
    op.drop_table('results')
    op.drop_index(op.f('ix_events_track_id'), table_name='events')
    op.drop_index(op.f('ix_events_name'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
